FROM ruby:3.0.2

# ENV BUNDLER_VERSION=2.1.4

RUN apt-get update -qq && apt-get install -y nodejs yarn \
 && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y libprotobuf-dev cmake protobuf-compiler

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn

RUN apt-get update && apt-get -y install cmake protobuf-compiler
RUN gem install bundler
RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle config build.nokogiri --use-system-libraries

RUN bundle check || bundle install

COPY . ./

ENTRYPOINT ["./entrypoints/docker-entrypoint.sh"]
