version: "3.8"
services:
  proxy:
    container_name: "cloud-sql-proxy"
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    ports:
      - 127.0.0.1:5432:5432
    command: "/cloud_sql_proxy -instances=jira-invoice-core:asia-northeast1:jira-core-db=tcp:0.0.0.0:5432"
